- civic_europe/templates/base.html
> temaplates: Use language_code from variable

- apps/ideas/templates/civic_europe_ideas/idea_list.html
- apps/ideas/templates/civic_europe_ideas/idea_update_form.html
- apps/ideas/templates/civic_europe_ideas/includes/call_to_action_tile.html
- apps/invites/templates/civic_europe_invites/invite_detail.html
- apps/invites/templates/civic_europe_invites/invite_form.html
- apps/journeys/templates/civic_europe_journeys/journey_entry_form.html
- civic_europe/assets/scss/components/_error_pages.scss
- civic_europe/assets/scss/components/_filters.scss
- civic_europe/assets/scss/components/_herounit.scss
- civic_europe/assets/scss/components/_ideas.scss
- civic_europe/assets/scss/core/_basics.scss
- civic_europe/assets/scss/core/_buttons.scss
- civic_europe/assets/scss/core/variables.scss
- civic_europe/templates/account/email_confirm.html
- civic_europe/templates/account/password_change.html
- civic_europe/templates/account/password_reset.html
- civic_europe/templates/account/password_reset_from_key.html
- civic_europe/templates/account/password_set.html
- civic_europe/templates/email_base.html
- civic_europe/templates/formtools/wizard/wizard_form.html
- cms/blog/templates/cms_blog/includes/blog_index_category_buttons.html
- cms/home/templates/cms_home/blocks/blog_block.html
- cms/home/templates/cms_home/blocks/call_to_action_block.html
- cms/home/templates/cms_home/includes/home_hero_unit.html
did this early for Marcello to start testing, might need a bit more work after the badges are being displayed and everything
> #2710: variable and colour update

- apps/ideas/admin.py
- apps/invites/templates/civic_europe_invites/emails/invite.en.email
- apps/journeys/templates/civic_europe_journeys/journey_entry_form.html
- apps/notifications/templates/civic_europe_notifications/emails/follow.en.email
- apps/notifications/templates/civic_europe_notifications/emails/notify_creator.en.email
- apps/notifications/templates/civic_europe_notifications/emails/notify_followers_community_award.en.email
- apps/notifications/templates/civic_europe_notifications/emails/notify_followers_new_comment.en.email
- apps/notifications/templates/civic_europe_notifications/emails/notify_followers_new_journey.en.email
- apps/notifications/templates/civic_europe_notifications/emails/notify_followers_shortlist.en.email
- apps/notifications/templates/civic_europe_notifications/emails/notify_followers_winner.en.email
- apps/notifications/templates/civic_europe_notifications/emails/submit_idea_notification.en.email
- apps/notifications/templates/civic_europe_notifications/emails/submit_journey_notification.en.email
- apps/users/filters.py
- apps/users/templates/civic_europe_users/includes/activity_list.html
- civic_europe/templates/account/email/email_confirmation_signup.en.email
- civic_europe/templates/email_base.html
- civic_europe/templates/email_base.txt
- tests/ideas/test_ideasketch_wizard.py
I have not checked all of them but ones I did worked, Kathi will test them all for formatting and correct wording from dev
> #2709 Pm 2020 03 emails

- package.json
- webpack.common.js
Reverts liqd/a4-civic-europe#6
> Revert "fix(deps): update dependency sass-loader to v8"

- package.json
- webpack.common.js
Reverts liqd/a4-civic-europe#82
> Revert "Revert "fix(deps): update dependency sass-loader to v8""

- requirements/base.txt
Reverts liqd/a4-civic-europe#81
> Revert "deps/python: revert update of django-crispy-forms"

- apps/ideas/templates/civic_europe_ideas/idea_detail.html
- apps/ideas/templates/civic_europe_ideas/includes/idea_detail_watch_btns.html
- apps/ideas/templates/civic_europe_ideas/includes/idealist_item.html
- civic_europe/assets/scss/all.scss
- civic_europe/assets/scss/components/_alert.scss
- civic_europe/assets/scss/components/_blocks.scss
- civic_europe/assets/scss/components/_comments.scss
- civic_europe/assets/scss/components/_wizard.scss
- civic_europe/assets/scss/components/navbar.scss
- civic_europe/assets/scss/core/_buttons.scss
- civic_europe/assets/scss/core/_dropdowns.scss
- civic_europe/assets/scss/core/variables.scss
- civic_europe/templates/includes/top_menu.html
- civic_europe/templates/socialaccount/connections.html
> Pm 2020 03 styling issues

- civic_europe/fixtures/idea-dev.json
> fixture/idea-dev: remove path to image

- apps/notifications/templates/civic_europe_notifications/emails/notify_creator.en.email
> apps/notifications: change footer of creator notification

- apps/ideas/static/civic_europe_ideas/SupportButton.jsx
- civic_europe/assets/images/placeholder_01.svg
- civic_europe/assets/images/placeholder_02.svg
- civic_europe/assets/js/civic_europe.js
- civic_europe/assets/scss/components/_blocks.scss
- civic_europe/assets/scss/components/_error_pages.scss
- civic_europe/assets/scss/components/_filters.scss
- civic_europe/assets/scss/components/_ideas.scss
- civic_europe/assets/scss/components/_slick_slider.scss
- civic_europe/assets/scss/core/_basics.scss
- civic_europe/assets/scss/core/_buttons.scss
- civic_europe/assets/scss/core/variables.scss
> #2759 Pm 2020 03 colours

- civic_europe/assets/scss/components/_filters.scss
- civic_europe/assets/scss/components/_ideas.scss
- civic_europe/assets/scss/core/_basics.scss
- civic_europe/templates/bootstrap3/layout/checkboxselectmultiple.html
> Pm 2020 03 styling issues fixes

- apps/invites/templates/civic_europe_invites/emails/invite.en.email
- apps/notifications/templates/civic_europe_notifications/emails/submit_idea_notification.en.email
> apps/emails: change wording and date format

- apps/ideas/forms.py
- apps/ideas/views.py
@fuzzylogic2000 this is super dumb but I tried the various different ways to format dates for django and python and they didn't work and the errors didn't really lead me anywhere so can you point me in right direction for how you would go about doing this?
> apps/ideas/forms: update wording fixes #140 soon

- apps/users/forms.py
Analogous to https://github.com/liqd/a4-meinberlin/pull/2890
> apps/account/forms: Check username for case insensitive uniqueness

- apps/ideas/views.py
> apps/ideas: change impact headline on detail page

- package.json
Reverts liqd/a4-civic-europe#199
> Revert "fix(deps): update dependency jquery to v3.5.0 [security]"

- package.json
Reverts liqd/a4-civic-europe#290
> Revert "fix(deps): update dependency mini-css-extract-plugin to v1.3.3"

- package.json
Reverts liqd/a4-civic-europe#288
> Revert "fix(deps): update dependency webpack-cli to v4"

- package.json
Reverts liqd/a4-civic-europe#284
> Revert "fix(deps): update dependency style-loader to v2"

- package.json
- webpack.common.js
reverts #217 as that couldn't be done automatically via github
> deps: revert copy webpack plugin update

- civic_europe/assets/scss/components/_ideas.scss
- civic_europe/assets/scss/components/_wizard.scss
- civic_europe/templates/bootstrap3/layout/radioselect.html
The height on the wizard form is clunky and not perfect but it's quick and other options would require more time and I already wasted quite a bit on that one
> Pm 2021 01 form design issue

- cms/home/templates/cms_home/simple_page.html
- cms/home/templates/cms_home/structured_text_page.html
Just a bit wider for now. Maybe we merge already for Kathi to check?
> cms/simple and structured pages: make container wider

- civic_europe/templates/formtools/wizard/wizard_form.html
> templates/formtools/wizard_form: remove typo

- cms/home/templates/cms_home/simple_page.html
- cms/home/templates/cms_home/structured_text_page.html
For the second commit, I think the clearfix would be cleaner to add to the blocks, but I was scared, that that could destroy sth. on the home page, so I added around the blocks.
> Kl 2021 02 wagtail

- civic_europe/assets/scss/components/_home.scss
@phillimorland That took me a while: first I tried teaching the fixed element it's width, which didn't work. In the end I went for this solution.
> cms/styling: make structured page sticky instead of fixed - fixes #401

- civic_europe/assets/js/app.js
- civic_europe/assets/js/bootstrap5-fix.js
> apps/comments: changing bootstrap5 attrs to bootstrap4
